[project]
name = "ml-final-pj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "myungjilee0914@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "transformers>=5.16.1",
]

[project.scripts]
ml-final-pj = "ml_final_pj:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
